# Generated by Django 5.2.7 on 2025-11-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bird",
            name="main_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black", "Black"),
                    ("white", "White"),
                    ("brown", "Brown"),
                    ("gray", "Gray"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("mixed", "Mixed/Multiple"),
                ],
                max_length=20,
            ),
        ),
    ]
