# Generated by Django 5.2.7 on 2025-11-30 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_logs", "0003_alter_bird_main_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="bird",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="bird",
            name="main_color",
            field=models.CharField(
                choices=[
                    ("black", "Black"),
                    ("white", "White"),
                    ("brown", "Brown"),
                    ("gray", "Gray"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("mixed", "Mixed/Multiple"),
                ],
                default="mixed",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Sighting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("sighting_date", models.DateField()),
                (
                    "bird",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bird_logs.bird"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "sightings",
            },
        ),
        migrations.DeleteModel(
            name="Entry",
        ),
    ]
