# Generated by Django 5.2.7 on 2025-11-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_logs", "0004_bird_description_alter_bird_main_color_sighting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bird",
            name="description",
            field=models.TextField(),
        ),
    ]
