# Generated by Django 5.2.7 on 2025-11-30 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bird_logs", "0005_alter_bird_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bird",
            unique_together={("text", "owner")},
        ),
    ]
